<?php require_once __DIR__.'/config/database.php';require_once __DIR__.'/config/auth.php';require_once __DIR__.'/config/helpers.php';if(isLoggedIn()){redirect(userRole()==='admin'?'admin/dashboard.php':(userRole()==='dosen'?'dosen/dashboard.php':'mahasiswa/dashboard.php'));}$error='';$role=$_POST['role']??'mahasiswa';if($_SERVER['REQUEST_METHOD']==='POST'){if(!checkCsrf($_POST['csrf']??null))$error='Sesi formulir tidak valid. Muat ulang halaman.';else{$username=trim($_POST['username']??'');$password=$_POST['password']??'';$st=$pdo->prepare('SELECT * FROM users WHERE username=? AND role=? LIMIT 1');$st->execute([$username,$role]);$u=$st->fetch();if($u && password_verify($password,$u['password'])){loginUser((int)$u['id'],$u['role']);if($u['role']==='mahasiswa'){$x=$pdo->prepare('SELECT nama FROM mahasiswa WHERE npm=?');$x->execute([$u['username']]);$_SESSION['display_name']=$x->fetchColumn()?:$u['username'];}elseif($u['role']==='dosen'){$x=$pdo->prepare('SELECT nama FROM dosen WHERE nidn=?');$x->execute([$u['username']]);$_SESSION['display_name']=$x->fetchColumn()?:$u['username'];}else $_SESSION['display_name']='Administrator';redirect($role==='admin'?'admin/dashboard.php':($role==='dosen'?'dosen/dashboard.php':'mahasiswa/dashboard.php'));}else $error='Username, role, atau password tidak sesuai.';}}$base='.';$assetBase='assets';$pageTitle='Masuk';require __DIR__.'/partials/head.php'; ?>
<div class="login-page"><div class="login-box"><a class="brand" href="index.php"><span class="brand-mark">✦</span><span><b>Sistem Absensi QR</b><small>Secure campus access</small></span></a><div class="auth-card" style="margin-top:25px"><span class="eyebrow">Welcome back</span><h2>Masuk ke sistem</h2><p>Gunakan akun terdaftar untuk melanjutkan.</p><?php if($error): ?><div class="notice error"><?=e($error)?></div><?php endif; ?><form method="post" autocomplete="off"><input type="hidden" name="csrf" value="<?=e(csrfToken())?>"><div class="role-tabs"><?php foreach(['mahasiswa'=>'Mahasiswa','dosen'=>'Dosen','admin'=>'Admin'] as $k=>$v): ?><button type="button" class="<?= $role===$k?'active':'' ?>" data-role="<?=$k?>"><?=$v?></button><?php endforeach; ?></div><input type="hidden" name="role" id="role" value="<?=e($role)?>"><div class="input-group"><label id="userLabel">NPM</label><div class="input-wrap"><input id="username" name="username" required placeholder="Masukkan NPM Anda"></div></div><div class="input-group"><label>Password</label><div class="input-wrap"><input type="password" name="password" required placeholder="Masukkan password Anda"></div></div><label style="display:flex;gap:9px;align-items:center;color:#a99eb1;font-size:11px"><input type="checkbox" name="remember"> Ingat saya</label><button class="btn btn-primary btn-block" type="submit">Masuk ke Sistem →</button></form><div class="register-prompt">
    <span>Belum punya akun?</span>
    <a href="register.php">Daftar sebagai mahasiswa</a>
</div>

<div class="helper">
    
</div></div></div></div><script>document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('role').value=b.dataset.role;document.getElementById('userLabel').textContent=b.dataset.role==='mahasiswa'?'NPM':(b.dataset.role==='dosen'?'NIDN':'Username');document.getElementById('username').placeholder='Masukkan '+(b.dataset.role==='mahasiswa'?'NPM':(b.dataset.role==='dosen'?'NIDN':'username'))+' Anda'});</script><?php require __DIR__.'/partials/footer.php'; ?>
